spring:
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  config:
    activate:
      on-profile: local

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:mem:HdJunctionTest'
    url: 'jdbc:h2:~/HdJunctionTest'
    username: testuser
    password: 1234!@#